services:
  node-app:
    build:
      args:
        - UPLOADS_DIR=${UPLOADS_DIR}}
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_URL=mongodb://db:27017
    networks:
      - services-network
    volumes:
      - offerly-uploads:${UPLOADS_DIR}
  db:
    image: mongo:latest
    volumes:
      - offerly-db-data:/data/db
    networks:
      - services-network

networks:
  services-network:

volumes:
  offerly-db-data:
  offerly-uploads:
