services:
  node-app:
    build:
      args:
        - DATA_DIR=${DATA_DIR}
        - COUNTRIES=${COUNTRIES}
        - CATEGORIES=${CATEGORIES}
        - LANGUAGES=${LANGUAGES}
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_URL=mongodb://db:27017
    networks:
      - services-network
  db:
    image: mongo:latest
    volumes:
      - offerly-db-data:/data/db
    networks:
      - services-network

networks:
  services-network:

volumes:
  offerly-db-data:
  offerly-static-data:
