services:
  node-app:
    build:
      dockerfile: Dockerfile.dev
      args:
        - UPLOADS_DIR=${UPLOADS_DIR}
    ports:
      - "8000:8000"
    env_file:
      - .local.env
    networks:
      - services-network
    volumes:
      - offerly-uploads:${UPLOADS_DIR}
      - ./src:/app/src
networks:
  services-network:

volumes:
  offerly-db-data:
  offerly-uploads:
